language: java
jdk:
  - oraclejdk8
services:
  - mongodb
#before_script: travis_wait 45 ./mvnw install -q -U -DskipTests=true -Pfast -Dmaven.test.redirectTestOutputToFile=true
script: mvn -B -V package docker:build
