logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

eebp:
  clientId: xxx
  clientSecret: xxx
  repoName: mltk-it-articles
  repoUser: mkyc
  repoMainDir: articles

google:
  analytics:
    trackingId: UA-XXXXXXXXX-X

---
spring:
  profiles: production
  data:
    mongodb:
      uri: mongodb://db:27017/eedb
